

CREATE TABLE SVX17737.DISTANCE_TRAVELLED
(
   DISTANCE_ID  INTEGER          GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1),
   DISTANCE     VARCHAR(10000),
   PERSON_NAME  VARCHAR(500),
   PERSON_ID    INTEGER,
   ISVISIBLE    VARCHAR(1)        DEFAULT 'Y',
   FROM_DATE    TIMESTAMP,
   TO_DATE      TIMESTAMP
);

ALTER TABLE SVX17737.DISTANCE_TRAVELLED
   ADD PRIMARY KEY (DISTANCE_ID);

COMMIT;
